/**
 * gpt-worker — Cloudflare Workers MCP server
 *
 * Exposes GPT-5.4 as a parallel worker pool for Claude (the overseer).
 * Claude delegates web research and document processing here, evaluates
 * the TL;DR results, and iterates until it has enough to answer the user.
 *
 * Deployed on Cloudflare Workers + Durable Objects via the `agents` SDK.
 * Add the public Worker URL to claude.ai → Settings → Integrations.
 *
 * Secrets (set via `wrangler secret put`):
 *   OPENAI_API_KEY — required
 *
 * Vars (set in wrangler.toml or Cloudflare dashboard):
 *   GPT_MODEL            default: gpt-5.4
 *   CHUNK_SIZE           default: 4000  (approx tokens per chunk)
 *   MAX_PARALLEL_REQUESTS default: 5
 */

import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

// ---------------------------------------------------------------------------
// Env bindings (generated by `wrangler cf-typegen`, manually listed here)
// ---------------------------------------------------------------------------
export interface Env {
  OPENAI_API_KEY: string;
  GPT_MODEL?: string;
  CHUNK_SIZE?: string;
  MAX_PARALLEL_REQUESTS?: string;
  MCP_OBJECT: DurableObjectNamespace;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Rough character-based chunking (≈4 chars per token). */
function chunkText(text: string, chunkSize: number): string[] {
  const chars = chunkSize * 4;
  const chunks: string[] = [];
  for (let i = 0; i < text.length; i += chars) {
    chunks.push(text.slice(i, i + chars));
  }
  return chunks.length > 0 ? chunks : [text];
}

/** Strip HTML tags and collapse whitespace for cleaner GPT input. */
function stripHtml(html: string): string {
  return html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
}

/** Fetch a URL and return its text content. */
async function loadUrl(url: string): Promise<string> {
  const resp = await fetch(url, {
    headers: { "User-Agent": "gpt-worker-mcp/1.0" },
  });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} fetching ${url}`);
  const ct = resp.headers.get("content-type") ?? "";
  const text = await resp.text();
  return ct.includes("html") ? stripHtml(text) : text;
}

/** Call OpenAI Chat Completions and return the assistant message. */
async function chatComplete(
  apiKey: string,
  model: string,
  messages: Array<{ role: string; content: string }>
): Promise<string> {
  const resp = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model, messages, max_tokens: 1024 }),
  });
  if (!resp.ok) {
    throw new Error(`OpenAI chat error ${resp.status}: ${await resp.text()}`);
  }
  const data = (await resp.json()) as {
    choices: Array<{ message: { content: string } }>;
  };
  return data.choices[0].message.content ?? "";
}

/** Call OpenAI Responses API (web_search_preview built-in tool). */
async function webSearch(
  apiKey: string,
  model: string,
  query: string,
  focus: string
): Promise<{ findings: string; sources: string[] }> {
  const resp = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      tools: [{ type: "web_search_preview" }],
      input: [
        `Focus on extracting information relevant to: ${focus}`,
        `Search query: ${query}`,
        "Return a concise TL;DR of the most relevant findings. Include key facts and source URLs.",
      ].join("\n\n"),
    }),
  });
  if (!resp.ok) {
    throw new Error(`OpenAI search error ${resp.status}: ${await resp.text()}`);
  }
  const data = (await resp.json()) as {
    output: Array<{
      type: string;
      content?: Array<{
        type: string;
        text?: string;
        annotations?: Array<{ url?: string }>;
      }>;
    }>;
  };

  let findings = "";
  const sources: string[] = [];
  for (const item of data.output ?? []) {
    if (item.type === "message") {
      for (const block of item.content ?? []) {
        if (block.type === "output_text" && block.text) {
          findings += block.text;
          for (const ann of block.annotations ?? []) {
            if (ann.url) sources.push(ann.url);
          }
        }
      }
    }
  }
  return { findings: findings.trim(), sources };
}

// ---------------------------------------------------------------------------
// MCP Agent (Durable Object backed)
// ---------------------------------------------------------------------------

export class GptWorkerMCP extends McpAgent<Env> {
  server = new McpServer({
    name: "gpt-worker",
    version: "1.0.0",
  });

  async init() {
    const env = this.env;
    const model = env.GPT_MODEL ?? "gpt-5.4";
    const chunkSize = parseInt(env.CHUNK_SIZE ?? "4000", 10);
    const maxParallel = parseInt(env.MAX_PARALLEL_REQUESTS ?? "5", 10);

    // ------------------------------------------------------------------
    // Tool: gpt_search
    // ------------------------------------------------------------------
    this.server.tool(
      "gpt_search",
      [
        "Search the web using GPT with built-in web search.",
        "Pass ALL queries you want to run at once — they are executed in parallel.",
        "focus describes what you ultimately want to find so GPT knows what to extract.",
        "Call this tool again with refined or broader queries if results are thin or off-topic.",
        "Returns an array of {query, findings, sources_used}.",
      ].join(" "),
      {
        queries: z
          .array(z.string())
          .describe("List of search queries to run in parallel"),
        focus: z
          .string()
          .describe(
            "What you ultimately want to find — guides GPT extraction and summarisation"
          ),
      },
      async ({ queries, focus }) => {
        const results: Array<{
          query: string;
          findings: string;
          sources_used: string[];
        }> = [];

        // Batch to respect MAX_PARALLEL_REQUESTS
        for (let i = 0; i < queries.length; i += maxParallel) {
          const batch = queries.slice(i, i + maxParallel);
          const batchResults = await Promise.all(
            batch.map(async (query) => {
              try {
                const { findings, sources } = await webSearch(
                  env.OPENAI_API_KEY,
                  model,
                  query,
                  focus
                );
                return { query, findings, sources_used: sources };
              } catch (e) {
                return {
                  query,
                  findings: `ERROR: ${String(e)}`,
                  sources_used: [],
                };
              }
            })
          );
          results.push(...batchResults);
        }

        return {
          content: [{ type: "text" as const, text: JSON.stringify(results, null, 2) }],
        };
      }
    );

    // ------------------------------------------------------------------
    // Tool: gpt_process
    // ------------------------------------------------------------------
    this.server.tool(
      "gpt_process",
      [
        "Load and summarize URLs or raw text using GPT.",
        "Each source is chunked by token count, each chunk summarised with the given focus, then consolidated.",
        "All sources are processed in parallel.",
        "Accepts URLs (fetched automatically) or raw text strings.",
        "Note: local file paths are not supported — use URLs or paste text directly.",
        "Returns an array of {source, summary, chunk_count}.",
        "Call again with a more specific focus if summaries miss key details.",
      ].join(" "),
      {
        sources: z
          .array(z.string())
          .describe(
            "List of URLs or raw text strings to process"
          ),
        focus: z
          .string()
          .describe(
            "What to extract — irrelevant content is filtered during summarisation"
          ),
      },
      async ({ sources, focus }) => {
        const results: Array<{
          source: string;
          summary: string;
          chunk_count: number;
        }> = [];

        for (let i = 0; i < sources.length; i += maxParallel) {
          const batch = sources.slice(i, i + maxParallel);
          const batchResults = await Promise.all(
            batch.map(async (source) => {
              try {
                const text =
                  source.startsWith("http://") ||
                  source.startsWith("https://")
                    ? await loadUrl(source)
                    : source;

                const chunks = chunkText(text, chunkSize);

                const chunkSummaries = await Promise.all(
                  chunks.map((chunk) =>
                    chatComplete(env.OPENAI_API_KEY, model, [
                      {
                        role: "system",
                        content: `You are a precise summarizer. Extract only what is relevant to: ${focus}. Be concise. Omit anything unrelated.`,
                      },
                      { role: "user", content: chunk },
                    ])
                  )
                );

                const summary =
                  chunkSummaries.length === 1
                    ? chunkSummaries[0]
                    : await chatComplete(env.OPENAI_API_KEY, model, [
                        {
                          role: "system",
                          content: `Consolidate these summaries into one coherent summary focused on: ${focus}. Remove repetition. Be concise.`,
                        },
                        {
                          role: "user",
                          content: chunkSummaries.join("\n\n---\n\n"),
                        },
                      ]);

                return { source, summary, chunk_count: chunks.length };
              } catch (e) {
                return {
                  source,
                  summary: `ERROR: ${String(e)}`,
                  chunk_count: 0,
                };
              }
            })
          );
          results.push(...batchResults);
        }

        return {
          content: [{ type: "text" as const, text: JSON.stringify(results, null, 2) }],
        };
      }
    );
  }
}

// ---------------------------------------------------------------------------
// Worker entry point
// ---------------------------------------------------------------------------
export default {
  fetch: GptWorkerMCP.serve("/mcp"),
};
